export const datas = {
  mockData: [
    {
      id: 1,
      title: "영상 제목",
      name: "게시자",
      viewCount: "조회수 100회",
      timeAgo: "1시간 전",
    },
    {
      id: 2,
      title: "영상 제목",
      name: "게시자",
      viewCount: "조회수 100회",
      timeAgo: "1시간 전",
    },
    {
      id: 3,
      title: "영상 제목",
      name: "게시자",
      viewCount: "조회수 100회",
      timeAgo: "1시간 전",
    },
    {
      id: 4,
      title: "영상 제목",
      name: "게시자",
      viewCount: "조회수 100회",
      timeAgo: "1시간 전",
    },
    {
      id: 5,
      title: "영상 제목",
      name: "게시자",
      viewCount: "조회수 100회",
      timeAgo: "1시간 전",
    },

    {
      id: 6,
      title: "영상 제목",
      name: "게시자",
      viewCount: "조회수 100회",
      timeAgo: "1시간 전",
    },
    {
      id: 7,
      title: "영상 제목",
      name: "게시자",
      viewCount: "조회수 100회",
      timeAgo: "1시간 전",
    },
    {
      id: 8,
      title: "영상 제목",
      name: "게시자",
      viewCount: "조회수 100회",
      timeAgo: "1시간 전",
    },
    {
      id: 9,
      title: "영상 제목",
      name: "게시자",
      viewCount: "조회수 100회",
      timeAgo: "1시간 전",
    },
    {
      id: 10,
      title: "영상 제목",
      name: "게시자",
      viewCount: "조회수 100회",
      timeAgo: "1시간 전",
    },
    {
      id: 11,
      title: "영상 제목",
      name: "게시자",
      viewCount: "조회수 100회",
      timeAgo: "1시간 전",
    },
    {
      id: 12,
      title: "영상 제목",
      name: "게시자",
      viewCount: "조회수 100회",
      timeAgo: "1시간 전",
    },
  ],
};
